### PR TITLE
fix:remove metadata.last-applied-configuration

### PR DESCRIPTION
**Pull request by apoorvanand**
issue-id: #8

### CODE REVIEW

**Comment by itaysk** [comment]
Perhaps you misunderstood the issue.. it's about removing just instances of `last-applied-configuration`; you removed all annotations entirely.

**Comment by itaysk** [comment]
Hi @apoorvanand , Are you planning to follow up with this PR? (It's ok if you don't just let me know)

**Comment by apoorvanand** [comment]
@itaysk  In this PR you need only the last state to be removed from metadata.Please confirm.

**Comment by apoorvanand** [comment]
@itaysk  In kubernetes official document site its mentioned as `kind: Deployment
metadata:
  annotations:
    # ...
    # This is the json representation of simple_deployment.yaml
    # It was written by kubectl apply when the object was created
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment",
      "metadata":{"annotations":{},"name":"nginx-deployment","namespace":"default"},
      "spec":{"minReadySeconds":5,"selector":{"matchLabels":{"app":nginx}},"template":{"metadata":{"labels":{"app":"nginx"}},
      "spec":{"containers":[{"image":"nginx:1.7.9","name":"nginx",
      "ports":[{"containerPort":80}]}]}}}}
  # ...
spec:
  # ...
  minReadySeconds: 5
  selector:
    matchLabels:
      # ...
      app: nginx
  template:
    metadata:
      # ...
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:1.7.9
        # ...
        name: nginx
        ports:
        - containerPort: 80
        # ...
      # ...
    # ...
  # ...`
Src :https://kubernetes.io/docs/tasks/manage-kubernetes-objects/declarative-config/
Can you please confirm what exactly you want not to be in your code.

**Comment by itaysk** [comment]
`metadata.annotations` should remain, but inside of it, the `kubectl.kubernetes.io/last-applied-configuration` annotations should be removed. The PR should include the code to remove it and the necessary changes to the tests.

**Comment by itaysk** [comment]
closing this one in favor of https://github.com/itaysk/kubectl-neat/pull/19

**Pull request closed without merging**
