### PR TITLE
feat(lists): support cleaning lists of resources

### LINKED ISSUE #11: support cleaning up a list of resources
This is a **feature** request.

While cleaning up a single resource is great, it could also be nice to clean up a whole list of resources.

For example, I would like to do `kubectl neat pod -n mynamespace -oyaml` in order to get all the uncluttered pods in my namespace.

I can make the PR if you find this useful :)

### PR DESCRIPTION
**Pull request by amirschw**
Enable cleaning up a list of resources, e.g. `kubectl neat pods -oyaml`

Closes #11

### CODE REVIEW

**Comment by itaysk** [comment]
Hi @amirschw should I close this PR or you want to pick it up again?

**Comment by amirschw** [comment]
Oh wow, this completely fell off my radar. Will be happy to pick this up again, thanks for your feedback!

**Comment by towolf** [comment]
@amirschw I'm really interested in this, too. Kubernetes 1.18.x has gotten quite cluttered.

**Comment by itaysk** [comment]
@towolf I'm happy to see you are interested in this feature. This should be an easy to implement feature so I am sure we can get it out soon.
@amirschw if you prefer to hand it over to me, please let me know. If you want to collaborate on this, I'm happy to jump on a quick call and finish this task.

**Comment by itaysk** [comment]
replaced by: https://github.com/itaysk/kubectl-neat/pull/32

**Pull request closed without merging**
