### PR TITLE
add support for releasing for windows platform

### LINKED ISSUE #6: Windows release
nothing really prohibits this plugin from running perfectly on windows. just need to add windows CI tests and builds.

- [ ] add e2e test that runs the tool on windows 
- [ ] modification to the makefile to cross compile a windows binary

### PR DESCRIPTION
**Pull request by karuppiah7890**
fixes #6 

- [x] Build for windows
- [x] Zip format for windows archive artifact - I see that zip is pretty usual thing in windows. If you don't feel so, we can change it. Reference - [goreleaser releases](https://github.com/goreleaser/goreleaser/releases), [helm releases](https://github.com/helm/helm/releases/)
- [ ] Run Tests on windows environment
- [ ] Add windows platform in the krew template yaml
- [ ] Make changes to Makefile - release and dist/* targets - invoke krew package script for windows too . Merge windows too from the list of JSON files

### CODE REVIEW

**Comment by karuppiah7890** [comment]
This is still just a draft

**Comment by karuppiah7890** [comment]
We run build and test alone in windows. If you think even build is not needed, then we can run test alone

**Comment by karuppiah7890** [comment]
I have changed it to run test alone in windows. For build - if we want to build and check compilation success for multiple platforms, we can try cross compilation in just ubuntu, maybe even use goreleaser instead of us doing it with make

**Comment by karuppiah7890** [comment]
I'll fix the file path separator issue in windows

**Comment by itaysk** [comment]
@karuppiah7890 thanks for picking this up! yes I didn't mean to build on a windows machine, I'm sure cross compilation will be good, just like you did.

One thing though is that I'd like to run the e2e test on windows as well before releasing

**Comment by karuppiah7890** [comment]
Currently there's no cross compilation happening in GitHub Actions CI, and I also didn't add anything. Just clarifying 😅

**Comment by karuppiah7890** [comment]
@itaysk I'm having difficulty in running the test in Windows. Reason: One of the tests is a blocker. The get command test. The error is usually always "file not found". I was not able to understand the exact reasoning for this. I have crossed out a few reasons.

Some more details
- The get command test uses kubectl-stub. The stub is written in bash. The windows environment has bash, but I think the `exec.Command` in Windows is working a bit differently and doesn't use bash to run the stub and tries to run the command directly and fails with same error "file not found" always. I have tried multiple things. The different things that I was suspicious of was -
- Wrong permissions on the script (executable mode)
- Failure of lookup of the script file
    - Script file extension (it has none currently) but Windows has some concept of `PATHEXT` 
- The shell in which the `go test` is running
- The shell in which the `exec.Command` is running
   - If the command is run with bash shell, then it will pickup the shebang and run it appropriately. But this would mean code change I think, as currently it looks like, for the same code, the command runs in different ways in different OSes. At least that's my guess.

There are different solutions to this. I'm not sure which you would prefer
- Have a windows script (powershell, batch or something) similar to kubectl-stub bash script and use that
- Use some other language, like even golang, to write the code for the stub. 
- Make code change to run with bash and check if it works but this would mean that all users need bash. Or, we need to change the code structure a bit to control more of how the kubectl is executed and control better in the test and try to run in bash just for test but not for users

Any thoughts? cc @itaysk

**Comment by itaysk** [comment]
@karuppiah7890 thanks for the effort! I will try to get a windows VM in order to troubleshoot.

**Comment by itaysk** [comment]
@karuppiah7890 today I have setup a windows dev env and troubleshooted through a number of incompatibility issues. now the following runs on windows: now `make build` rubs on windows, and I manually tested the result it looks ok. also `make test` (now the unit tests), and `make test-e2e` passes successfully. also make test.

I also made the changes to `make test-integration` so that it can work, but it fails. I then realized that although the executable works, kubectl can't use it as a plugin from some reason, saying "identified as a kubectl plugin, but it is not executable"

I can't spend more time on this now, my work is under the branch "windows", if you want to pick it up.

Note that development experience still required bash and coreutils. (just for dev, not for the end user).
The easiest way is to install git bash for windows and `export PATH=/usr/bin:$PATH` to make sure there aren't tooling conflicts.

**Comment by karuppiah7890** [comment]
I actually don't have access to a windows machine. I was just using a test github repo with windows CI environment to test stuff for the code, but no manual test with actual `kubectl`

**Comment by karuppiah7890** [comment]
I'll close this PR as I'm not working on this and don't have access to a windows machine which seems like a necessary thing

**Pull request closed without merging**
